### ISSUE TITLE
Skin of retribution bug

### ISSUE THREAD

**Issue by QuantumOwl** [SolastaMods/SolastaUnfinishedBusiness#2734]
if you cast it on an ally (via sorcerer's shared spell invocation) the second character will get the temp HP but not the thorn effect

**Comment by ThyWoof** [comment]
Fixed on [DEV](https://github.com/SolastaMods/SolastaUnfinishedBusiness/commit/402bef1cb0ef265bdcdf15b66652d0230a05fe1c). Thanks.

**Comment by QuantumOwl** [comment]
@ThyWoof I updated to 1.4.33.60 and Skin of retribution still doesnt seem to be working when casting it on two characters (using Shared Spell metamagic). I created two new characters and leveled the sorcerer up to 3, went into a custom campaign (a simple room with 1 low level enemy I control) and Skin of retribution still only applies to the sorcerer and not the second character. (Both characters get the Temp HP, but the second character does not get the reflect damage applied to him)
