### ISSUE TITLE
Weapon Master Fighter - Momentum ability reduces Action Surge to a single attack

### ISSUE THREAD

**Issue by Tichrimo** [SolastaMods/SolastaUnfinishedBusiness#3148]
[AutoSave_1.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11413072/AutoSave_1.zip)
Unfinished Business v. 1.4.33.83
Solasta Build ID: 10260630

Steps to Reproduce
1. Fighter level 5+ with Extra Attack kills a creature with his second attack
2. Fighter is prompted to use his reaction to activate Momentum, and uses that attack
3. Fighter activates Action Surge

Expected Result
- Fighter gets 2 attacks with Action Surge

Observed Result
- Fighter only gets 1 attack with Action Surge

**Comment by ThyWoof** [comment]
This is an engine limitation. Still couldn’t find a way to solve this problem. Won’t fix in short term.

**Comment by Tichrimo** [comment]
Gotcha.  Good to know!

  Ian

**Comment by ThyWoof** [comment]
Do you have a save I could use for test?

**Comment by Tichrimo** [comment]
I attached one to the bug report

**Comment by ThyWoof** [comment]
Ops. I’m trying to find a resolution on this one again

**Comment by Tichrimo** [comment]
Cool!  Good luck!

**Comment by ThyWoof** [comment]
![image](https://user-images.githubusercontent.com/13087646/236651712-8eec9153-292f-4105-96d6-448210c85a91.png)
fixed

**Comment by ThyWoof** [comment]
Released. Pls confirm on your end

**Comment by Tichrimo** [comment]
Hey there,

Still not fixed.  My Action Surge should grant two extra attacks, but
Momentum still eats up one of them.
[image: image.png]

**Comment by Tichrimo** [comment]
Attached the proper save file this time :)

**Comment by Tichrimo** [comment]
[AutoSave_2.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11413741/AutoSave_2.zip)

**Comment by ThyWoof** [comment]
Will test on yours but you can see from my screenshot that I attacked 3 times and after action surge had 2 attacks available. Strange
