### ISSUE TITLE
Ritual Casting unavailable to Gnome Spellmaster

### ISSUE THREAD

**Issue by seameth** [SolastaMods/SolastaUnfinishedBusiness#3285]
Playing Crown of the Magister campaign.  using UB 1.5.46.1

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/44379243/0bda0470-252c-4bd5-8fec-439590fa06e7)

Have done a RESPEC, still unable to cast spells ritually. 

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/44379243/53b3532b-6769-4da6-a4ec-8690e816b121)

Ritual Casting is listed amongst my class features. 

My Cleric is able to Ritually Cast though. 

![image](https://github.com/SolastaMods/SolastaUnfinishedBusiness/assets/44379243/c6626121-93cd-4091-9475-b0effd47405b)

**Comment by ThyWoof** [comment]
fixed on 1.5.46.2.

**Comment by seameth** [comment]
Btw, I still don't have Ritual Casting for my Gnome Wizard Spellmaster. 

[wizard bug .zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/11583724/wizard.bug.zip)
