### ISSUE TITLE
Is there a better way to implement the 2nd-level spell 'Darkness'?

### ISSUE THREAD

**Issue by Milliuna** [SolastaMods/SolastaUnfinishedBusiness#3572]
The 2nd-level spell 'Darkness' in base-game Solasta works nothing like Darkness from the table-top. In Solasta, it essentially works like Fog Cloud, just costing a 2nd-level spell slot, only imposing Disadvantage to made attacks and attacks recieved. What it should do is provide total concealment to everyone in it, and make creatures inside it Blinded. Currently, Devil's Sight, Blind Sight and Tremor Sense eliminate the Disadvantage on the attacking side, but don't provide Advantage from being an unseen attacker, which unfortuately breaks a Devil's Sight + Darkness synergy from Warlocks. 

I've searched for the topic in the closed topics but only found a tangentially related thread on the topic of Blind Fighting. Is there any chance this could be fixed on the mod's end, or is Darkness' terminal implementation something only Tactical Adventurer could fix? Maybe some hacky solution, by making people in the Darkness count as Invisible, like with the spell?

**Comment by HIEROT** [comment]
This is virtually solved in the mod, you just enable advantage to no darkness (whatsoever name) option, this includes case of darkness

**Comment by Milliuna** [comment]
> This is virtually solved in the mod, you just enable advantage to no darksight (whatsoever name) option, this includes case of darkness

While this is toggle solves one of the problems, it doesn't solve the other, which is creatures external to the Darkness can still see creatures within Darkness as valid targets for spells that require sight. This makes saving throw spells just as potent regardless.

I'm guessing since the topic has been closed, this isn't possible...?
