### ISSUE TITLE
instability warning

### ISSUE THREAD

**Issue by PrOZacKU3** [SolastaMods/SolastaUnfinishedBusiness#4116]
it seems to soft lock with random spells. it happened when i cast ice storm and also twice with lightning bolt. also my monk will sometimes lose his 2nd main attack action. 
[Player.log](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12874894/Player.log)
[Forsaken Isle.txt](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12874913/Forsaken.Isle.txt)

i couldn't upload my save because the file type isn't supported so i tired switching it to .txt if that's right

**Comment by ThyWoof** [comment]
We also need a save

**Comment by PrOZacKU3** [comment]
i just edited my comment, i tried switching it to txt. is that ok?

**Comment by ThyWoof** [comment]
It won’t open. Zip and attach

**Comment by PrOZacKU3** [comment]
[Forsaken Isle.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12874960/Forsaken.Isle.zip)
thats the save 

[Player.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12874965/Player.zip)
and the log too if you needed both.

**Comment by PrOZacKU3** [comment]
My apologies if this turns out to just be a be patient and wait for a patch situation but if this was supposed to fix it I'm still getting an instability issue when I load that save. I updated the mod via the mod manager and when that didn't work just re-downloaded the latest zip and also still have the issue. Again, my bad if I'm just being impatient, I'm not totally familiar with the whole modding process etc.

**Comment by ThyWoof** [comment]
Fixed in DEV. It will be on next release. You are being impatient.

**Comment by PrOZacKU3** [comment]
Awesome, my fault, thank you for everything I didn't understand

**Comment by PrOZacKU3** [comment]
I'm still getting an instability warning whenever I load this save. I didn't know if I should open a new issue since it's the same file. To maybe help I know for sure that upcasting lightning bolt to lvl 4 makes it soft lock whenever it hits. Also I don't know if this is normal behavior but I did notice that if I load that save, get the warning, quit back to the menu and re load it doesn't give the warning again but I don't know if that's just because it already said it once. It will still lock on casting spells, most particularly lightning bolt lvl 4 and ice storm

**Comment by ThyWoof** [comment]
It looks like I’ll have to take Prozac myself to fix this 😂

**Comment by ThyWoof** [comment]
The problem is happening with the Feat Poisonous Skin. Unfortunately it's a recurrent effect so I believe only way to fix on your save is to RESPEC the hero with it. Please give a try and let me know.

**Comment by ThyWoof** [comment]
[Uploading SolastaUnfinishedBusiness.zip…]()
replace DLL you have in mod folder with this one and let me know.

**Comment by ThyWoof** [comment]
[SolastaUnfinishedBusiness.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12896479/SolastaUnfinishedBusiness.zip)

this DLL should fix your issue. Please replace the one you have in the mod folder.

**Comment by PrOZacKU3** [comment]
HEY HEEEYYY!!! That got it!! Thank you!! I really appreciate the quick fix!! Thanks again for everything!!

**Comment by PrOZacKU3** [comment]
So, I spoke too soon, I got excited. It definitely froze when upcasting lightning bolt again. The warning popped up after the cast and before damage. I am right next to a rest so I can respec right away if that's the best solution. Absolutely no problem to do that, sorry for the premature confirmation

**Comment by ThyWoof** [comment]
[SolastaUnfinishedBusiness.zip](https://github.com/SolastaMods/SolastaUnfinishedBusiness/files/12906679/SolastaUnfinishedBusiness.zip)

here. please test this one and let me know.

**Comment by PrOZacKU3** [comment]
Sweet!! Sorry it took so long to get back to ya I wanted to be more sure this time ha ha! There was a very specific scenario I wanted to test before I said anything. It seemed to regularly occur whenever I had both spike growth and spirit guardian in play before trying to cast and it works now as well as any other time! I really appreciate you taking the time for such a particular problem.

**Comment by ThyWoof** [comment]
No worries. Official fix on next version.
