### ISSUE TITLE
Wendigo character has lost reach

### ISSUE THREAD

**Issue by Bawookles** [SolastaMods/SolastaUnfinishedBusiness#4792]
This just happened with the new 1.5.97.18 update. My Wendigo barbarian has lost his "Natural Lunger" ability which gives him an extra 5 feet of reach with melee weapons. If you look at this save, he can't make a melee attack on the orc from two squares away, but has to move adjacent to the orc to attack.

Thanks. Saved file attached. 
[No Reach.sav.zip](https://github.com/user-attachments/files/16136068/No.Reach.sav.zip)

**Comment by ThyWoof** [comment]
replace your DLL with this one as it'll take another couple of days before I have a fix release. in this DLL:

- fixed Great Weapon Master attack mode modifier, and additional attack validator
- fixed Lunging Attack maneuver increase weapon reach validator
- fixed Martial Battle Master maneuvers pool amount at 3rd
- fixed Martial Psi Warrior force of will saving throw behavior
- fixed Power Attack attack mode modifier
- fixed Powerful metamagic interaction with Sunbeam spell
- fixed Path of the Wild Magic wild surge attack mode modifier
- fixed Wendigo natural lunger increase weapon reach validator

[SolastaUnfinishedBusiness.zip](https://github.com/user-attachments/files/16136238/SolastaUnfinishedBusiness.zip)

**Comment by Bawookles** [comment]
Hi, ThyWoof.

Thanks for that DLL, I replaced my previous one but unfortunately it didn't change the problem, my Wendigo still doesn't have reach.
