### ISSUE TITLE
Battle Smith Artificer should use INT for attack and damage rolls with magical weapons

### ISSUE THREAD

**Issue by CptTinman** [SolastaMods/SolastaUnfinishedBusiness#5081]
Battle Smith Artificer subclass's feature called Inventive Weapon Use is not functioning, and is not allowing the character to use intelligence for attack and damage rolls with magic weapons (the weapon in question is an infusion). 
[yay 4.zip](https://github.com/user-attachments/files/17939133/yay.4.zip)

**Comment by ThyWoof** [comment]
Already fixed in dev. Thanks for save.

**Comment by Sabbelwookie** [comment]
The feature (Inventive Weapon Use INT to attack and damage) is NOT fixed. Just playing as a Battle Smith with v1.5.97, UMM v27.10 and UB 1.5.97.45, and the feat is not working. Maybe there is something I am doing wrong?...
